// packages/react/src/use-suspense-store.ts
import { useSyncExternalStore } from 'react';
import type { AsyncState } from '@stardust/core';
import type { StoreContract, UnwrapContext } from '@stardust/core';

// ── Pending promise registry ──────────────────────────────────────────────────
// WeakMap keyed by store instance. Entries are removed when the store emits
// any update (i.e. the async operation settled), so the next pending transition
// creates a fresh Promise. No memory leak: WeakMap releases entries when the
// store is GC'd.
const pendingPromises = new WeakMap<object, Promise<void>>();

function getOrCreatePendingPromise(
  store: Pick<StoreContract<unknown>, 'subscribe'>
): Promise<void> {
  const cached = pendingPromises.get(store);
  if (cached !== undefined) {
    return cached;
  }

  // Promise.withResolvers() (ES2024) — resolve handle is available before the
  // subscribe callback is declared, eliminating the temporal-dependency between
  // the Promise executor and the unsubscribe reference.
  const { promise, resolve } = Promise.withResolvers<void>();
  const unsubscribe = store.subscribe(() => {
    pendingPromises.delete(store);
    unsubscribe();
    resolve();
  });

  pendingPromises.set(store, promise);
  return promise;
}

// ── Internal types ────────────────────────────────────────────────────────────

/** @internal */
type SuspenseStoreContract<TSnapshot> = StoreContract<TSnapshot> & {
  setContext?: (ctx: unknown) => void;
};

// ── useSuspenseStore ──────────────────────────────────────────────────────────

/**
 * Subscribe to an `AsyncState<T>` field in a store using the React Suspense
 * protocol.
 *
 * | `AsyncState` status | Behaviour                                             |
 * | ------------------- | ----------------------------------------------------- |
 * | `fulfilled`         | Returns `T` directly                                  |
 * | `rejected`          | Throws the stored `Error` (caught by `<ErrorBoundary>`) |
 * | `idle` / `pending`  | Throws a Promise (caught by `<Suspense>`)              |
 *
 * The thrown Promise resolves on the next store emission, causing React to
 * retry the render. A store subscription (`useSyncExternalStore`) keeps the
 * component in sync so it re-renders as soon as the async state settles.
 *
 * Wrap the consuming component in `<Suspense fallback={…}>` for the loading
 * UI and pair with an `<ErrorBoundary>` to handle rejected states.
 *
 * @example
 * function UserProfile() {
 *   const user = useSuspenseStore(userStore, (s) => s.user);
 *   return <div>{user.name}</div>;
 * }
 *
 * // With context injection:
 * function UserProfile() {
 *   const user = useSuspenseStore(userStore, (s) => s.user, { context: apiClient });
 *   return <div>{user.name}</div>;
 * }
 *
 * // Mount site:
 * <ErrorBoundary fallback={<p>Error</p>}>
 *   <Suspense fallback={<p>Loading…</p>}>
 *     <UserProfile />
 *   </Suspense>
 * </ErrorBoundary>
 */
// Overload 1 — no context
export function useSuspenseStore<TSnapshot, T>(
  store: StoreContract<TSnapshot>,
  select: (snapshot: TSnapshot) => AsyncState<T>
): T;
// Overload 2 — with context injection
export function useSuspenseStore<TSnapshot, T, TContext>(
  store: StoreContract<TSnapshot> & {
    readonly setContext: (ctx: UnwrapContext<TContext>) => void;
  },
  select: (snapshot: TSnapshot) => AsyncState<T>,
  options: { readonly context: UnwrapContext<TContext> }
): T;
// Implementation
export function useSuspenseStore<TSnapshot, T>(
  store: SuspenseStoreContract<TSnapshot>,
  select: (snapshot: TSnapshot) => AsyncState<T>,
  options?: { readonly context?: unknown }
): T {
  if (options?.context !== undefined) {
    store.setContext?.(options.context);
  }

  const state = useSyncExternalStore(store.subscribe, () => select(store.getSnapshot()));

  if (state.status === 'fulfilled') {
    return state.data;
  }
  if (state.status === 'rejected') {
    throw state.error;
  }

  // idle or pending — suspend until the store emits its next update
  // eslint-disable-next-line @typescript-eslint/only-throw-error -- Suspense protocol requires throwing a Promise
  throw getOrCreatePendingPromise(store);
}

// packages/solid/src/use-suspense-store.ts
/**
 * @experimental SolidJS Suspense adapter for Stardust async stores.
 *
 * Requires `solid-js` installed in the consumer's project.
 * Not included in the main library build or barrel exports.
 */
import { createResource } from 'solid-js';
import type { AsyncState } from '@stardust/core';
import type { StoreContract } from '@stardust/core';
import { useStore } from './use-store';

/**
 * Subscribe to an `AsyncState<T>` field in a store using the SolidJS Suspense
 * protocol.
 *
 * | `AsyncState` status | Behaviour                                              |
 * | ------------------- | ------------------------------------------------------ |
 * | `fulfilled`         | Returns `T` via the resource accessor                  |
 * | `rejected`          | Throws the stored `Error` (caught by `<ErrorBoundary>`) |
 * | `idle` / `pending`  | Suspends (caught by `<Suspense>`)                       |
 *
 * Returns a SolidJS resource accessor `() => T`. Wrap the consuming component
 * in `<Suspense fallback={…}>` and `<ErrorBoundary>`.
 *
 * @example
 * function UserProfile() {
 *   const user = useSuspenseStore(userStore, (s) => s.user);
 *   return <div>{user().name}</div>;
 * }
 *
 * // Mount site:
 * <ErrorBoundary fallback={(e) => <p>{e.message}</p>}>
 *   <Suspense fallback={<p>Loading…</p>}>
 *     <UserProfile />
 *   </Suspense>
 * </ErrorBoundary>
 */
export function useSuspenseStore<TSnapshot, T>(
  store: StoreContract<TSnapshot>,
  select: (snapshot: TSnapshot) => AsyncState<T>
): () => T {
  // Track the AsyncState slice as a reactive signal. The signal updates only
  // when the AsyncState reference changes (Object.is equality by default).
  const state = useStore(store, select);

  // createResource re-runs the fetcher whenever `state` (the source) changes.
  // — fulfilled → resolves immediately with the data
  // — rejected  → rejects, ErrorBoundary catches the thrown error
  // — idle/pending → returns a never-resolving Promise so Suspense waits;
  //   when the store emits the next update the source signal changes and
  //   createResource re-fetches with the new AsyncState.
  const [resource] = createResource(state, (asyncState): Promise<T> => {
    if (asyncState.status === 'fulfilled') {
      return Promise.resolve(asyncState.data);
    }
    if (asyncState.status === 'rejected') {
      return Promise.reject(asyncState.error);
    }
    return new Promise<T>(() => {});
  });

  return () => {
    const value = resource();
    if (value === undefined) {
      throw new Error('[useSuspenseStore] resource not ready — wrap the component in <Suspense>');
    }

    return value;
  };
}
